### ISSUE TITLE
color mesh.

### ISSUE THREAD

**Issue by tiexuedanxin** [lioryariv/idr#14]
hello, is there some way to construct the color mesh?

**Comment by lioryariv** [comment]
Hey, 
Since the learned light field depends also on the view direction, you need to fix some view direction for each node (or the same for all nodes) and then you can determine the color of the nodes by querying the rendering network -  M(x,n,v,z), where x is the position, n (normal) and z (feature vector) are given from the implicit network, and the determined v (view direction).
