### ISSUE TITLE
Geometric initialisation

### ISSUE THREAD

**Issue by theFilipko** [lioryariv/idr#34]
I would like to ask you, how to modify the geometric initialisation part for the case, where the output from the positional encoding does not contain the raw XYZ and consist only of sin and cos of the XYZ at various frequencies? Thank you.

**Comment by lioryariv** [comment]
I would say trying to zero-out all the encoding part from the first sine, since around 0 sin(x)~x.
Meaning, if the encoding is phi(x) = [sin(x),cos(x),sin(2x),cos(2x),....], so the first layer should be:
W*phi(x) = W1*sin(x)+W2* [cos(x),sin(2x),cos(2x),....]
Where W1 is initialized as the first layer of the geometric initialization and W2 initialized with 0 (similar to the current situation).

Hope that helps!
